mn_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("projects.urls")),
    path("admin/", admin.site.urls),
]

projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.ProjectListView.as_view(), name="project_list"),
    path("project/create", views.ProjectCreateView.as_view(), name="project_create"),
    path("project/edit/<int:pk>", views.ProjectUpdateView.as_view(), name="project_update"),
    path("project/delete/<int:pk>", views.ProjectDeleteView.as_view(), name="project_delete"),
    path("task/create", views.TaskCreateView.as_view(), name="task_create"),
    path("task/edit/<int:pk>", views.TaskUpdateView.as_view(), name="task_update"),
    path("task/delete/<int:pk>", views.TaskDeleteView.as_view(), name="task_delete")
]

accounts/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.conf.global_settings import AUTH_USER_MODEL


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class ProjestStatue(models.IntegerChoices):
    PENDING = 1, "pending"
    COMPLETED = 2, "completed"
    POSTPONED = 3, "postponed"
    CANCELED = 4, "canceled"


class Project(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    statue = models.IntegerField(
        choices=ProjestStatue.choices,
        default=ProjestStatue.PENDING,
        null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    user = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )  # ما لازم نسوي class user لانه موجود في جانجو

    def __str__(self):
        return self.title


class Task(models.Model):
    description = models.TextField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.description

projects/forms.py
from django import forms
from . import models


class ProjectCreateForm(forms.ModelForm):
    class Meta:
        model = models.Project
        fields = ['category', 'title', 'description']
        widgets = {
            'category': forms.Select(),
            'title': forms.TextInput(),
            'description': forms.Textarea()
        }


class ProjectUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Project
        fields = ['category', 'title', 'statue']
        widgets = {
            'category': forms.Select(),
            'title': forms.TextInput(),
            'statue': forms.Select()
        }

accounts/views.py
from django.shortcuts import render

# Create your views here.

projects/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from . import models
from . import forms


class ProjectListView(ListView):
    model = models.Project
    template_name = "project/list.html"


class ProjectCreateView(CreateView):
    model = models.Project
    form_class = forms.ProjectCreateForm
    template_name = "project/create.html"
    success_url = reverse_lazy("project_list")


class ProjectUpdateView(UpdateView):
    model = models.Project
    form_class = forms.ProjectUpdateForm
    template_name = "project/update.html"

    def get_success_url(self):
        return reverse("project_update", args=[self.object.id])


class ProjectDeleteView(DeleteView):
    model = models.Project
    template_name = "project/delete.html"
    success_url = reverse_lazy("project_list")

class TaskCreateView(CreateView):
    model = models.Task
    fields = ['project', 'description']
    http_method_names = ['post']

    def get_success_url(self):
        return reverse("project_update", args=[self.object.project.id])


class TaskUpdateView(UpdateView):
    model = models.Task
    fields = ['is_completed']
    http_method_names = ['post']

    def get_success_url(self):
        return reverse("project_update", args=[self.object.project.id])

class TaskDeleteView(DeleteView):
    model = models.Task
        
    def get_success_url(self):
        return reverse("project_update", args=[self.object.project.id])

projects/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <title>Django Projects Management</title>
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

projects/templates/project/create.html
{% load i18n %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit"  />
    </form>
{% endblock %}

projects/templates/project/delete.html
{% load i18n %}
{% block content %}
    <p>Are you sure?</p>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit"  />
    </form>
{% endblock %}

projects/templates/project/list.html
{% load i18n %}
{% block content %}
    <h3>{% trans "My Project" %}</h3>
    <ul>
        {% for project in object_list %}
            <li>{{ project.title }} <a href="{% url 'project_update' project.id %}">Edit</a></li>
        {% empty %}
            <li>{% trans "There are no projects to show" %}</li>
        {% endfor %}
    </ul>
{% endblock %}

projects/templates/project/task.html
{% load i18n %}

<ul>
    {% for task in project.task_set.all %}
        <li>
            <form method= "post" action="{% url 'Task_update' task.id %}">
                {% csrf token %}
                <input
                    type="checkbox"
                    name="is_completed"
                    {% if task.is_completed $} checked {% endif %}
                    onchange="this.form.submit()"
                />
                {{ task.description }}
             </form>
                <form method= "post" action="{% url 'Task_delete' task.id %}">
                    {% csrf token %}
                    <button type="submit">Delete</button>
                </form>
        </li>
    {% endfor %}
</ul>

<form method="post" action="{% url 'Task_Create' %}">
    {% csrf_token %}
    <input type="hidden" value="{{ project.id }}" name="project">
    <input type="text" name="description" placeholder="{% trans 'New Task' %}">
    <input type="submit" value="{% trans 'Add' %}">
</form>

projects/templates/project/update.html
{% load i18n %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit"  />
    </form>
    <a href="{% url 'Project_Delete' object_id %}">Delete</a>
    {% include 'project/task.html' with project=object %}
{% endblock %}